//
//  Defines.m
//  EC_SDK_DEMO
//
//  Created by EC Open support team.
//  Copyright(C), 2017, Huawei Tech. Co., Ltd. ALL RIGHTS RESERVED.
//

#import "Defines.h"

#pragma mark - Login
NSString *const UPORTAL_LOGIN_EVT_RESULT_KEY = @"UPORTAL_LOGIN_EVT_RESULT_KEY";
NSString *const LOGIN_FIREWALL_DETECT_RESULT = @"LOGIN_FIREWALL_DETECT_RESULT";
NSString *const LOGIN_FIREWALL_MODE_KEY = @"LOGIN_FIREWALL_MODE_KEY";          // value: TUP_FIREWALL_MODE
NSString *const LOGIN_STG_TUNNEL_CREATE_RESULT_KEY = @"LOGIN_STG_TUNNEL_CREATE_RESULT_KEY";


#pragma mark - Call
NSString *const SIP_STATUS_KEY              = @"SIP_STATUS_KEY";
NSString *const CALL_ERROR_CODE             = @"CALL_ERROR_CODE";
NSString *const CALL_ID                     = @"CALL_ID";
NSString *const CALL_TYPE                   = @"CALL_TYPE";
NSString *const CALL_CLOSE_REASON           = @"CALL_CLOSE_REASON";
NSString *const CALL_COMMING_NUMBER         = @"CALL_COMMING_NUMBER";
NSString *const CALL_VIDEO_OPERATION        = @"CALL_VIDEO_OPERATION";
NSString *const CALL_VIDEO_OPERATION_RESULT = @"CALL_VIDEO_OPERATION_RESULT";
NSString *const CALL_VIDEO_ORIENT_KEY       = @"CALL_VIDEO_ORIENT_KEY";
NSString *const TSDK_CALL_INFO_KEY          = @"TSDK_CALL_INFO_KEY";
NSString *const TSDK_CALL_HOLD_RESULT_KEY    = @"TSDK_CALL_HOLD_RESULT_KEY";
NSString *const TSDK_CALL_UNHOLD_RESULT_KEY  = @"TSDK_CALL_UNHOLD_RESULT_KEY";
NSString *const TSDK_CALL_TRANSFER_RESULT_KEY = @"TSDK_CALL_TRANSFER_RESULT_KEY";
NSString *const TUP_CALL_SET_IPT_RESULT_KEY = @"TUP_CALL_SET_IPT_RESULT_KEY";
NSString *const TUP_CALL_IPT_ENUN_KEY       = @"TUP_CALL_IPT_ENUN_KEY";
NSString *const TSDK_CALL_RINGBACK_KEY      = @"TSDK_CALL_RINGBACK_KEY";
NSString *const TUP_CALL_SESSION_MODIFIED_KEY       = @"TUP_CALL_SESSION_MODIFIED_KEY";
NSString *const AUDIO_ROUTE_KEY            = @"AUDIO_ROUTE_KEY";
NSString *const TSDK_VIEW_REFRESH_KEY            = @"TSDK_VIEW_REFRESH_KEY";
NSString *const TSDK_AUX_REASONCODE_KEY    = @"TSDK_AUX_REASONCODE_KEY";

//CTD
NSString *const TSDK_CTD_CALL_RESULT_KEY      = @"TSDK_CTD_CALL_RESULT_KEY";
NSString *const TSDK_CTD_CALL_STATE_KEY       = @"TSDK_CTD_CALL_STATE_KEY";
//confid

NSString *const TUP_CALL_DATACONF_ID_KEY       = @"TUP_CALL_DATACONF_ID_KEY";
#pragma mark - Conference

NSString *const CREATE_MEETING_FAILED_CODE_KEY = @"CREATE_MEETING_FAILED_CODE_KEY";
NSString *const TUP_SITE_KEY = @"TUP_SITE_KEY";
NSString *const CONF_ATTENDEE_LIST_KEY = @"CONF_ATTENDEE_LIST_KEY";
NSString *const CONF_MEETING_HANDLE_KEY = @"CONF_MEETING_HANDLE_KEY";
NSString *const CONF_HANDLE_KEY = @"CONF_HANDLE_KEY";
NSString *const CONF_OPERATION_SITE_RESULT_KEY = @"CONF_OPERATION_SITE_RESULT_KEY";
NSString *const CONF_RELEASE_CHAIRMAN_RESULT_KEY = @"CONF_RELEASE_CHAIRMAN_RESULT_KEY";
NSString *const CONF_LOCAL_SITE_BROCAST_STATUS_KEY = @"CONF_LOCAL_SITE_BROCAST_STATUS_KEY";
NSString *const CONF_POSTPONE_SITE_RESULT_KEY = @"CONF_POSTPONE_SITE_RESULT_KEY";
NSString *const CONF_CURRENT_EXISTS_CHAIRMAN_KEY = @"CONF_CURRENT_EXISTS_CHAIRMAN_KEY";
NSString *const MEETING_FORCE_RELEASE_CHAIRMAN_NOTIFY_KEY = @"MEETING_FORCE_RELEASE_CHAIRMAN_NOTIFY_KEY";
NSString *const CONF_REST_OF_TIME_KEY = @"CONF_REST_OF_TIME_KEY";
NSString *const CONF_S_CALL_EVT_CONF_CONNECTED = @"CONF_S_CALL_EVT_CONF_CONNECTED";

//EC3.0

NSString *const UCCONF_CONFDATA_KEY = @"UCCONF_CONFDATA_KEY";
NSString *const UCCONF_END_KEY = @"UCCONF_END_KEY";
NSString *const UCCONF_INCOMMING_KEY = @"UCCONF_INCOMMING_KEY";
NSString *const UCCONF_RESULT_KEY = @"UCCONF_RESULT_KEY";

NSString *const UCCONF_SET_PERSENTER_RESULT_KEY = @"UCCONF_SET_PERSENTER_RESULT_KEY";
NSString *const UCCONF_SET_HOST_RESULT_KEY = @"UCCONF_SET_HOST_RESULT_KEY";
NSString *const UCCONF_OLDPERSENTER_KEY = @"UCCONF_OLDPERSENTER_KEY";
NSString *const UCCONF_OLDHOST_KEY = @"UCCONF_OLDHOST_KEY";
NSString *const UCCONF_NEWPERSENTER_KEY = @"UCCONF_NEWPERSENTER_KEY";
NSString *const UCCONF_NEWHOST_KEY = @"UCCONF_NEWHOST_KEY";

NSString *const DATACONF_SHARE_DATA_KEY = @"DATACONF_SHARE_DATA_KEY";
NSString *const DATACONF_FINISH_SHARE_KEY = @"DATACONF_FINISH_SHARE";
NSString *const DATACONF_VIDEO_ON_SWITCH_KEY = @"DATACONF_VIDEO_ON_SWITCH_KEY";
NSString *const DATACONF_VIDEO_ON_SWITCH_USERID_KEY = @"DATACONF_VIDEO_ON_SWITCH_USERID_KEY";
NSString *const DATACONF_VIDEO_ON_NOTIFY_KEY = @"DATACONF_VIDEO_ON_NOTIFY_KEY";
NSString *const DATACONF_USER_LEAVE_KEY = @"DATACONF_USER_LEAVE_KEY";
NSString *const DATACONF_USER_ENTER_KEY = @"DATACONF_USER_ENTER_KEY";
NSString *const DATACONF_CHAT_MSG_KEY = @"DATACONF_CHAT_MSG_KEY";
NSString *const DATACONF_REMOTE_CAMERA_KEY = @"DATACONF_REMOTE_CAMERA_KEY";
NSString *const ECCONF_HAND_UP_RESULT_KEY = @"ECCONF_HAND_UP_RESULT_KEY";//


//EC6.0
NSString *const ECCONF_RESULT_KEY = @"ECCONF_RESULT_KEY";
NSString *const ECCONF_SVC_LIST_KEY = @"ECCONF_SVC_LIST_KEY";
NSString *const ECCONF_CURRENTCONF_DETAIL_KEY = @"ECCONF_CURRENTCONF_DETAIL_KEY";
NSString *const ECCONF_BOOK_CONF_INFO_KEY   = @"ECCONF_BOOK_CONF_INFO_KEY";

NSString *const ECCONF_MUTE_KEY = @"ECCONF_MUTE_KEY";
NSString *const ECCONF_HANDUP_STATUS_KEY = @"ECCONF_HANDUP_STATUS_KEY";  // 举手后状态通知

NSString *const ECCONF_DATA_CONF_BFCP_KEY = @"ECCONF_DATA_CONF_BFCP_KEY";

NSString *const TUP_CALL_DECODE_SUCCESS_NOTIFY = @"TUP_CALL_DECODE_SUCCESS_NOTIFY";

NSString *const TUP_CALL_REMOVE_CALL_VIEW_NOTIFY = @"TUP_CALL_REMOVE_CALL_VIEW_NOTIFY";

NSString *const TUP_CONF_INCOMING_KEY = @"TUP_CONF_INCOMING_KEY";

NSString *const LOGIN_UNREGISTERED_RESULT = @"LOGIN_UNREGISTERED_RESULT";
NSString *const SRTP_TRANSPORT_MODE = @"SRTP_TRANSPORT_MODE";

NSString *const MAA_LOGIN_SUCCESSED = @"MAA_LOGIN_SUCCESSED"; // 登录成功
NSString *const MAA_LOGIN_FAILED = @"MAA_LOGIN_FAILED"; // 登录失败

NSString *const USE_IDO_CONFCTRL = @"USE_IDO_CONFCTRL";

NSString *const USER_ACCOUNT        = @"USER_ACCOUNT";
NSString *const USER_PASSWORD       = @"USER_PASSWORD";


NSString *const LOGIN_LOGOUT_SUCCESS_KEY = @"LOGIN_LOGOUT_SUCCESS_KEY";

NSString *const LOGIN_RECONNECTION_SUCCESS_KEY = @"LOGIN_RECONNECTION_SUCCESS_KEY";         // 二次重连成功的回调KEY
NSString *const LOGIN_USER_OFFLINE_SUCCESS_KEY = @"LOGIN_USER_OFFLINE_SUCCESS_KEY";         // 用户离线成功的回调KEY

NSString *const LOGIN_GET_USER_INFO_SUCCESS_KEY = @"LOGIN_GET_USER_INFO_SUCCESS_KEY";       // 登录用户数据更新KEY

NSString *const LOGIN_SIP_ACCOUNT_HAVE_LOGINED_KEY = @"LOGIN_SIP_ACCOUNT_HAVE_LOGINED_KEY";  // sip帐号已登录

NSString *const LOGIN_AUTH_FAILED = @"LOGIN_AUTH_FAILED";   // 登录授权失败

NSString *const CONF_JOIN_DATA_RESOULT = @"CONF_JOIN_DATA_RESOULT";  // 加入数据会议通知

//虚拟会议室
NSString *const VIRTUAL_MEETING_ROOM_LISTS_KEY = @"VIRTUAL_MEETING_ROOM_LIST_KEY";
NSString *const VIRTUAL_MEETING_VMR_3_ID_SAVE_KEY = @"VIRTUAL_MEETING_VMR_3_ID_SAVE_KEY";
NSString *const VIRTUAL_MEETING_VMR_2_ID_SAVE_KEY = @"VIRTUAL_MEETING_VMR_2_ID_SAVE_KEY";
NSString *const VIRTUAL_MEETING_VMR_CHIRMAN_PWD_SAVE_KEY = @"VIRTUAL_MEETING_VMR_CHIRMAN_PWD_SAVE_KEY";


NSString *const E_CONF_REQUEST_CHAIRMAN_NOTIFY = @"E_CONF_REQUEST_CHAIRMAN_NOTIFY";
NSString *const E_CONF_RELEASE_CHAIRMAN_NOTIFY = @"E_CONF_RELEASE_CHAIRMAN_NOTIFY";

//NSString *const ECCONF_SVC_LIST_KEY = @"ECCONF_SVC_LIST_KEY"; //svc列表

NSString *const DATA_CONF_AUX_STREAM_BIND_NOTIFY = @"DATA_CONF_AUX_STREAM_BIND_NOTIFY";


// 登陆业务通知
NSString *const LOGIN_C_GET_TEMP_USER_INFO_FAILD = @"LOGIN_C_GET_TEMP_USER_INFO_FAILD";
NSString *const LOGIN_C_FORCE_LOGOUT_SUCCESS_KEY = @"LOGIN_C_FORCE_LOGOUT_SUCCESS_KEY";

// 用户认证类型
NSString *const CALL_EVT_AUTH_TYPE_KEY = @"CALL_EVT_AUTH_TYPE_KEY";

// 呼叫事件通知 
NSString *const CALL_S_COMING_CALL_NOTIFY = @"CALL_S_COMING_CALL_NOTIFY";
NSString *const CALL_S_CALL_EVT_CALL_ROUTE_CHANGE = @"CALL_S_CALL_EVT_CALL_ROUTE_CHANGE";
NSString *const CALL_S_CALL_EVT_CALL_RINGBACK = @"CALL_S_CALL_EVT_CALL_RINGBACK";
NSString *const CALL_S_CALL_EVT_CALL_OUTGOING = @"CALL_S_CALL_EVT_CALL_OUTGOING";
NSString *const CALL_S_CALL_EVT_CALL_CONNECTED = @"CALL_S_CALL_EVT_CALL_CONNECTED";
NSString *const CALL_S_CALL_EVT_CALL_MODIFY = @"CALL_S_CALL_EVT_CALL_MODIFY";
NSString *const CALL_S_CALL_EVT_CALL_ENDED = @"CALL_S_CALL_EVT_CALL_ENDED";
NSString *const CALL_S_CALL_EVT_CALL_DESTROY = @"CALL_S_CALL_EVT_CALL_DESTROY";
NSString *const CALL_S_CALL_EVT_REFRESH_VIEW_IND = @"CALL_S_CALL_EVT_REFRESH_VIEW_IND";
NSString *const CALL_S_CALL_EVT_OPEN_VIDEO_REQ = @"CALL_S_CALL_EVT_OPEN_VIDEO_REQ";
NSString *const CALL_S_CONF_QUITE_TO_CONFLISTVIEW = @"CALL_S_CONF_QUITE_TO_CONFLISTVIEW";
NSString *const CALL_S_CALL_EVT_CLOSE_VIDEO_IND = @"CALL_S_CALL_EVT_CLOSE_VIDEO_IND";
NSString *const CALL_S_CALL_EVT_OPEN_VIDEO_IND = @"CALL_S_CALL_EVT_OPEN_VIDEO_IND";
NSString *const CALL_S_CALL_EVT_REFUSE_OPEN_VIDEO_IND = @"CALL_S_CALL_EVT_REFUSE_OPEN_VIDEO_IND";
NSString *const CALL_S_CALL_EVT_AUX_DATA_RECVING = @"CALL_S_CALL_EVT_AUX_DATA_RECVING";
NSString *const CALL_S_CONF_CALL_EVT_DATA_START = @"CALL_S_CONF_CALL_EVT_DATA_START";
NSString *const CALL_S_CALL_EVT_AUX_SHARE_FAILED = @"CALL_S_CALL_EVT_AUX_SHARE_FAILED";
NSString *const CALL_S_CALL_EVT_AUX_DATA_STOPPED = @"CALL_S_CALL_EVT_AUX_DATA_STOPPED";
NSString *const CALL_S_CALL_EVT_DECODE_SUCCESS = @"CALL_S_CALL_EVT_DECODE_SUCCESS";
NSString *const CALL_S_CALL_EVT_NO_STREAM_DURATION = @"CALL_S_CALL_EVT_NO_STREAM_DURATION";
NSString *const CALL_S_CALL_EVT_AUDIT_DIR = @"CALL_S_CALL_EVT_AUDIT_DIR";
NSString *const CALL_S_CALL_EVT_REFER_NOTIFY = @"CALL_S_CALL_EVT_REFER_NOTIFY";
NSString *const CALL_S_CALL_EVT_VIDEO_NET_QUALITY = @"CALL_S_CALL_EVT_VIDEO_NET_QUALITY";
NSString *const CALL_S_CALL_EVT_AUDIO_NET_QUALITY = @"CALL_S_CALL_EVT_AUDIO_NET_QUALITY";
NSString *const CALL_S_CALL_EVT_HOWL_STATUS = @"CALL_S_CALL_EVT_HOWL_STATUS";
NSString *const CALL_S_CONF_EVT_BROADCAST_IND = @"CALL_S_CONF_EVT_BROADCAST_IND";
NSString *const CALL_S_CALL_EVT_BAND_WIDTH_CHANGE = @"CALL_S_CALL_EVT_BAND_WIDTH_CHANGE";


// 处理呼叫保持回调业务
NSString *const CALL_S_CALL_EVT_HOLD_SUCCESS = @"CALL_S_CALL_EVT_HOLD_SUCCESS";
NSString *const CALL_S_CALL_EVT_HOLD_FAILED = @"CALL_S_CALL_EVT_HOLD_FAILED";
NSString *const CALL_S_CALL_EVT_UNHOLD_SUCCESS = @"CALL_S_CALL_EVT_UNHOLD_SUCCESS";


// 处理会控业务回调
NSString *const CALL_S_CONF_EVT_JOIN_CONF_RESULT = @"CALL_S_CONF_EVT_JOIN_CONF_RESULT";
NSString *const CALL_S_CONF_EVT_BOOK_CONF_RESULT = @"CALL_S_CONF_EVT_BOOK_CONF_RESULT";
NSString *const CALL_S_CONF_EVT_QUERY_CONF_LIST_RESULT = @"CALL_S_CONF_EVT_QUERY_CONF_LIST_RESULT";
NSString *const CALL_S_CONF_EVT_QUERY_CONF_DETAIL_RESULT = @"CALL_S_CONF_EVT_QUERY_CONF_DETAIL_RESULT";
NSString *const CALL_S_CONF_EVT_INFO_AND_STATUS_UPDATE = @"CALL_S_CONF_EVT_INFO_AND_STATUS_UPDATE";



// 会控操作结果
NSString *const CALL_S_CONF_MUTE_CONF_SUCSESS = @"CALL_S_CONF_MUTE_CONF_SUCSESS";
NSString *const CALL_S_CONF_UNMUTE_CONF_SUCSESS = @"CALL_S_CONF_UNMUTE_CONF_SUCSESS";
NSString *const CALL_S_CONF_MUTE_ATTENDEE = @"CALL_S_CONF_MUTE_ATTENDEE";
NSString *const CALL_S_CONF_UNMUTE_ATTENDEE = @"CALL_S_CONF_UNMUTE_ATTENDEE";           
NSString *const CALL_S_CONF_ADD_ATTENDEE = @"CALL_S_CONF_ADD_ATTENDEE";
NSString *const CALL_S_CONF_SET_HANDUP = @"CALL_S_CONF_SET_HANDUP";
NSString *const CALL_S_CONF_CANCLE_HANDUP = @"CALL_S_CONF_CANCLE_HANDUP";
NSString *const CALL_S_CONF_SET_VIDEO_MODE = @"CALL_S_CONF_SET_VIDEO_MODE";
NSString *const CALL_S_CONF_WATCH_ATTENDEE = @"CALL_S_CONF_WATCH_ATTENDEE";
NSString *const CALL_S_E_CONF_POSTPONE_CONF = @"CALL_S_E_CONF_POSTPONE_CONF";
NSString *const CALL_S_CONF_BROADCAST_ATTENDEE = @"CALL_S_CONF_BROADCAST_ATTENDEE";
NSString *const CALL_S_CONF_CANCEL_BROADCAST_ATTENDEE = @"CALL_S_CONF_CANCEL_BROADCAST_ATTENDEE";
NSString *const CALL_S_CONF_REQUEST_CHAIRMAN = @"CALL_S_CONF_REQUEST_CHAIRMAN";
NSString *const CALL_S_CONF_RELEASE_CHAIRMAN = @"CALL_S_CONF_RELEASE_CHAIRMAN";
NSString *const CALL_S_CONF_ROLL_CALL = @"CALL_S_CONF_ROLL_CALL";
NSString *const CALL_S_CONF_EVT_SPEAKER_IND = @"CALL_S_CONF_EVT_SPEAKER_IND";
NSString *const CALL_S_CONF_EVT_SVC_WATCH_IND = @"CALL_S_CONF_EVT_SVC_WATCH_IND";
NSString *const CALL_S_CONF_EVT_GET_VMR_LIST_RESULT = @"CALL_S_CONF_EVT_GET_VMR_LIST_RESULT";
NSString *const CALL_S_CONF_EVT_SVC_WATCH_POLICY_IND = @"CALL_S_CONF_EVT_SVC_WATCH_POLICY_IND";
NSString *const CALL_S_CONF_EVT_CHECKIN_RESULT = @"CALL_S_CONF_EVT_CHECKIN_RESULT";
NSString *const CALL_S_CONF_EVT_HAND_UP_IND = @"CALL_S_CONF_EVT_HAND_UP_IND";
NSString *const CALL_S_CONF_EVT_DEVICE_STATE = @"CALL_S_CONF_EVT_DEVICE_STATE";

NSString *const CALL_S_CONF_BASEINFO_UPDATE_KEY = @"CALL_S_CONF_BASEINFO_UPDATE_KEY";

// 服务器设置
NSString *const SERVER_CONFIG_INFO = @"SERVER_CONFIG_INFO";
NSString *const CONFIG_SERVER_ADDR = @"CONFIG_SERVER_ADDR";
NSString *const CONFIG_SERVER_PORT = @"CONFIG_SERVER_PORT";
NSString *const DICT_SAVE_LOGIN_userName = @"SAVE_LOGIN_userName";
NSString *const SAVE_USER_CONUT = @"SAVE_USER_CONUT";

 

NSString *const LOGIN_STATUS_LINK_JOINMEETING_SUCCESS = @"LOGIN_STATUS_LINK_JOINMEETING_SUCCESS";
NSString *const LOGIN_STATUS_LINK_JOINMEETING_ERROR = @"LOGIN_STATUS_LINK_JOINMEETING_ERROR";
 
NSString *const UPLOAD_LOG_RESULT = @"UPLOAD_LOG_RESULT";

NSString *const RECENT_CONTACT_REFRESH_DATA = @"RECENT_CONTACT_REFRESH_DATA";

@implementation Defines

@end
